export const DIVISIONS = [
  { key: 'casper', name: 'CASPER GROUP', sub: 'Food & Beverage', color: '#D4603A', icon: '🍽',
    brands: ['Angel Wings','Pasta Bish','Taco Yaki','Patty Daddy','Espresso Co','Morning After',"Toss'd",'Sweet Tooth','Mojo Juice','Mr. Oyster'] },
  { key: 'huglife', name: 'HUGLIFE', sub: 'Events & Experiences', color: '#9C27B0', icon: '🎪',
    brands: ['Espresso','Gangsta Gospel',"Sunday's Best",'Shut Up & Dance','Napkin King','Paparazzi','Pawchella','Black Ball','Beauty & The Beast'] },
  { key: 'umbrella', name: 'UMBRELLA GROUP', sub: 'Services', color: '#1E88E5', icon: '☂',
    brands: ['Umbrella Auto Exchange','Umbrella Injury Network','Umbrella Realty Group','Umbrella Clean Services',"The People's Dept.",'Umbrella Accounting','The Brand Studio','The Automation Office','The Mind Studio','Umbrella Legal & Compliance'] },
  { key: 'bodegea', name: 'BODEGEA', sub: 'Products', color: '#43A047', icon: '📦',
    brands: ['Infinity Water','Pronto Energy','Noir','Stush'] },
  { key: 'scented', name: 'SCENTED FLOWERS', sub: 'Museum Series', color: '#E91E63', icon: '🌺',
    brands: ['Forever Futbol','Living Legends','Women Make The World','Fallen Stars'] },
  { key: 'opulence', name: 'OPULENCE DESIGNS', sub: 'Art', color: '#FF9800', icon: '🎨',
    brands: ['Torches','Angel & Astronauts','Izzy','Country Boy'] },
  { key: 'playmakers', name: 'PLAYMAKERS', sub: 'Non-Profit', color: '#00BCD4', icon: '⚽',
    brands: ['Sole Exchange',"Let's Talk About It"] },
  { key: 'innercircle', name: 'INNER CIRCLE', sub: 'Apps', color: '#7C4DFF', icon: '📱',
    brands: ['Good Times','Roadside','On Call'] },
];

export const WORKFLOWS = [
  { id: 'T7ZOnFaSEvcYvwbM', name: 'Content Factory', cat: 'content', webhook: '/webhook/content-campaign' },
  { id: 'bGdwLiVFcqP0FcIG', name: 'PR Send Pitch', cat: 'outreach', webhook: null },
  { id: 'rrGMta9UjYxkPcgz', name: 'Social Inbox', cat: 'social', webhook: '/webhook/social-inbox' },
  { id: '0paDyU807bccvZYQ', name: 'Influencer Outreach', cat: 'outreach', webhook: null },
  { id: 'ya3S4B89sgViCZY7', name: 'Competitive Monitoring', cat: 'intel', webhook: null },
  { id: 'ca5RBVlllApR4F61', name: 'Event Launch Engine', cat: 'events', webhook: '/webhook/event-launch' },
  { id: 'LcSKrYBhoMOvK0YD', name: 'Brand Voice', cat: 'content', webhook: '/webhook/brand-voice-analyze' },
  { id: '3RZbP7GLiYqztNRO', name: 'Lead Revenue', cat: 'sales', webhook: '/webhook/lead-revenue' },
  { id: 'gY9i3dPy3UIvjU00', name: 'Casper Ops', cat: 'ops', webhook: null },
  { id: 'vk5Rd1MO5YnGhHrF', name: 'Vendor Ops', cat: 'ops', webhook: null },
  { id: '7sSvlSzCeIx2SdQ2', name: 'Webhook Health', cat: 'system', webhook: null },
  { id: 'kf48VVHafFcqkm1I', name: 'Command Authority', cat: 'system', webhook: '/webhook/command-authority' },
  { id: 'RlKxBDXVEL5u1ztH', name: 'Failure Intelligence', cat: 'system', webhook: null },
  { id: 'yGGm5IVIqFGprFBn', name: 'Scheduled Messenger', cat: 'outreach', webhook: '/webhook/schedule-text' },
  { id: 'm1JYqHCsULRYvwMZ', name: 'Contact Sourcer', cat: 'sales', webhook: '/webhook/source-contacts' },
  { id: 'IccJ2L56lxKI2FKv', name: 'Social Send DMs', cat: 'social', webhook: '/webhook/send-dms' },
  { id: 'bKyPsFlvQ6xSvVzr', name: 'Social Message Gen', cat: 'social', webhook: '/webhook/social-message-gen' },
  { id: 'FJfgKLj7sXHqYBjR', name: 'LINDA Dispatch', cat: 'system', webhook: '/webhook/linda' },
];

export const EVENTS_2026 = [
  { name: 'Espresso', date: '2026-04-17', city: 'DC', series: 'espresso' },
  { name: 'Taste of Art', date: '2026-04-24', city: 'LA', series: 'tasteofart' },
  { name: 'Shut Up & Dance', date: '2026-05-02', city: 'Charlotte', series: 'shutup' },
  { name: 'Taste of Art', date: '2026-05-15', city: 'ATL', series: 'tasteofart' },
  { name: 'Napkin King', date: '2026-05-23', city: 'ATL', series: 'napkin' },
  { name: "Sunday's Best", date: '2026-05-24', city: 'TBD', series: 'sundays' },
  { name: 'Espresso', date: '2026-05-29', city: 'LA', series: 'espresso' },
  { name: 'Paparazzi', date: '2026-05-31', city: 'LA', series: 'paparazzi' },
  { name: 'Espresso', date: '2026-06-05', city: 'Charlotte', series: 'espresso' },
  { name: 'Taste of Art', date: '2026-06-12', city: 'DC', series: 'tasteofart' },
  { name: 'Paparazzi (BET)', date: '2026-06-14', city: 'LA', series: 'paparazzi' },
  { name: 'Gangsta Gospel', date: '2026-06-19', city: 'ATL', series: 'gangsta' },
  { name: 'Birthday Houston', date: '2026-06-27', city: 'Houston', series: 'birthday' },
  { name: 'Birthday ATL', date: '2026-07-02', city: 'ATL', series: 'birthday' },
  { name: 'Birthday Vegas', date: '2026-07-04', city: 'Vegas', series: 'birthday' },
  { name: "Sunday's Best", date: '2026-07-05', city: 'TBD', series: 'sundays' },
  { name: 'Taste of Art', date: '2026-07-10', city: 'Houston', series: 'tasteofart' },
  { name: 'Paparazzi', date: '2026-07-12', city: 'DC', series: 'paparazzi' },
  { name: 'Napkin King', date: '2026-07-18', city: 'Houston', series: 'napkin' },
  { name: 'Shut Up & Dance', date: '2026-07-25', city: 'ATL', series: 'shutup' },
  { name: 'Espresso', date: '2026-07-31', city: 'LA', series: 'espresso' },
  { name: 'Gangsta Gospel', date: '2026-08-01', city: 'Houston', series: 'gangsta' },
  { name: 'Espresso', date: '2026-08-07', city: 'ATL', series: 'espresso' },
  { name: 'Paparazzi', date: '2026-08-09', city: 'Charlotte', series: 'paparazzi' },
  { name: 'Taste of Art', date: '2026-08-14', city: 'Houston', series: 'tasteofart' },
  { name: 'Pawchella', date: '2026-08-22', city: 'ATL', series: 'pawchella' },
  { name: 'Napkin King', date: '2026-08-29', city: 'LA', series: 'napkin' },
  { name: 'Espresso', date: '2026-09-04', city: 'DC', series: 'espresso' },
  { name: 'Gangsta Gospel', date: '2026-09-05', city: 'LA', series: 'gangsta' },
  { name: "Sunday's Best", date: '2026-09-06', city: 'TBD', series: 'sundays' },
  { name: 'Beauty & Beast', date: '2026-09-12', city: 'ATL', series: 'beauty' },
  { name: 'Paparazzi', date: '2026-09-13', city: 'ATL', series: 'paparazzi' },
  { name: 'Napkin King', date: '2026-09-19', city: 'Charlotte', series: 'napkin' },
  { name: 'Shut Up & Dance', date: '2026-09-26', city: 'LA', series: 'shutup' },
  { name: 'Haunted House', date: '2026-10-01', city: 'ATL', series: 'haunted' },
  { name: 'Napkin King Finale', date: '2026-10-10', city: 'TBD', series: 'napkin' },
  { name: "Monster's Ball", date: '2026-10-31', city: 'TBD', series: 'monsters' },
  { name: 'Black Ball', date: '2026-11-21', city: 'ATL', series: 'blackball' },
  { name: "Sunday's Best", date: '2026-11-29', city: 'TBD', series: 'sundays' },
  { name: 'Taste of Art Basel', date: '2026-12-04', city: 'Miami', series: 'tasteofart' },
  { name: 'Snow Ball', date: '2026-12-12', city: 'ATL', series: 'snowball' },
];

export const WORKFLOW_CATEGORIES: Record<string, { label: string; color: string }> = {
  content: { label: 'Content', color: 'text-status-warning' },
  outreach: { label: 'Outreach', color: 'text-status-info' },
  social: { label: 'Social', color: 'text-status-pink' },
  intel: { label: 'Intel', color: 'text-status-purple' },
  events: { label: 'Events', color: 'text-status-cyan' },
  sales: { label: 'Sales', color: 'text-status-success' },
  ops: { label: 'Ops', color: 'text-muted-foreground' },
  system: { label: 'System', color: 'text-status-error' },
};
